embedding_model: Qwen/Qwen3-Embedding-0.6B
embedding_type: local
max_turns: 50

dataset:
  name: alfworld

evolve:
  split: train

evaluate:
  split: valid_unseen

selector: uniform

skill_evolving:
  name: expel
  mode: spg_online
  insight_strategy: incremental
  rollouts_per_task: 1
  evaluation_rollouts_per_task: 1
  temperature: 0.3
  max_tokens: 1024
  evaluation_temperature: 0.3
  evaluation_max_tokens: 1024
  enable_dynamic_update: true
  use_learned_memory_during_evolve: true
  max_reflection_depth: 3
  success_critique_num: 8
  top_k: 2
  max_fewshot_tokens: 1000
  max_num_rules: 20
  reflection_max_tokens: 4096
  insight_max_tokens: 4096
  reflection_temperature: 0.0
