embedding_model: all-MiniLM-L6-v2
embedding_type: local
max_turns: 51
dataset: alfworld

warmup:
  split: valid_seen
  n_warm: 60
  tasks_per_type: 10

evolve:
  split: valid_seen
  task_types: all
  tasks_per_type: 0

experiment:
  n_bandit: 100
  seed: 42

evaluate:
  split: valid_unseen
  task_types: all
  tasks_per_type: 0

selector: spg_bandit

skill_evolving:
  name: simple_agent

spg_bandit:
  K: 2
  alpha: 0.1
  d_f: 16
  tau: 0.1
