embedding_model: all-MiniLM-L6-v2
embedding_type: local
max_turns: 51

warmup:
  split: valid_seen
  n_tasks: 60
  steps: 60

evolve:
  split: valid_seen
  n_tasks: 60
  steps: all

evaluate:
  split: valid_unseen
  n_tasks: 0
  steps: all

selector: spg_bandit

skill_evolving:
  name: simple_agent

spg_bandit:
  K: 4
  alpha: 0.1
  d_f: 16
  tau: 0.1
